export const ROLES = {
    ADMIN: "ADMIN",
    MAIRIE: "MAIRIE",
    DIRECTRICE: "DIRECTRICE",
    PROFESSEUR: "PROFESSEUR",
};

export const PERMISSIONS = {
    ACCESS_DASHBOARD: [ROLES.ADMIN],
    INSCRIPTION_ELEVE: [ROLES.MAIRIE],
    IMPORT_ELEVE: [ROLES.MAIRIE],
    CLOTURE_ANNEE: [ROLES.DIRECTRICE],
    NOTIFICATION_PROFESSEUR: [ROLES.DIRECTRICE],
    VALIDATION_REDOUBLEMENT: [ROLES.DIRECTRICE],
    CONSULTATION_LISTE_ELEVE: [ROLES.PROFESSEUR, ROLES.DIRECTRICE],
    INDICATION_REDOUBLEMENT: [ROLES.PROFESSEUR],
};
